# Exoplanet Analysis

Goal:
Analyze confirmed exoplanets to understand size, stellar energy, and detection confidence.

Steps:
- Filter confirmed planets
- Clean relevant features
- Create size categories
- Analyze distributions
- Export for Tableau

Import block

In [1]:
import pandas as pd
import numpy as np
from google.colab import files

Collab Block

In [2]:
from google.colab import drive
path = '/content/drive/MyDrive/exoplanets.csv'

df = pd.read_csv(path)

Column Exploration

In [3]:

df.columns.tolist()

['kepid',
 'kepoi_name',
 'kepler_name',
 'koi_disposition',
 'koi_pdisposition',
 'koi_score',
 'koi_fpflag_nt',
 'koi_fpflag_ss',
 'koi_fpflag_co',
 'koi_fpflag_ec',
 'koi_period',
 'koi_period_err1',
 'koi_period_err2',
 'koi_time0bk',
 'koi_time0bk_err1',
 'koi_time0bk_err2',
 'koi_impact',
 'koi_impact_err1',
 'koi_impact_err2',
 'koi_duration',
 'koi_duration_err1',
 'koi_duration_err2',
 'koi_depth',
 'koi_depth_err1',
 'koi_depth_err2',
 'koi_prad',
 'koi_prad_err1',
 'koi_prad_err2',
 'koi_teq',
 'koi_teq_err1',
 'koi_teq_err2',
 'koi_insol',
 'koi_insol_err1',
 'koi_insol_err2',
 'koi_model_snr',
 'koi_tce_plnt_num',
 'koi_tce_delivname',
 'koi_steff',
 'koi_steff_err1',
 'koi_steff_err2',
 'koi_slogg',
 'koi_slogg_err1',
 'koi_slogg_err2',
 'koi_srad',
 'koi_srad_err1',
 'koi_srad_err2',
 'ra',
 'dec',
 'koi_kepmag']

# filter confirmed discoveries only and keep columns relevant to question

In [4]:
df_raw = df.copy()

df_confirmed = df_raw[df_raw['koi_disposition'] == 'CONFIRMED']

df_confirmed = df_confirmed[['kepoi_name','koi_prad','koi_insol','koi_score']].dropna()

df_confirmed = df_confirmed.sort_values(by='koi_score', ascending=False)
df_confirmed.head()

     kepoi_name  koi_prad  koi_insol  koi_score
8817  K06863.01      0.95       4.20        1.0
0     K00752.01      2.26      93.59        1.0
7612  K03371.02      1.00      50.05        1.0
4     K00755.01      2.75     926.16        1.0
5     K00756.01      3.90     114.81        1.0

Size Categories

In [5]:
df_confirmed['size_category'] = pd.cut(
    df_confirmed['koi_prad'],
    bins=[0,1.5,3,6,20]
    ,labels=['earth-like','super-earth-like','neptune-like','Gas-Giant']

)
df_confirmed.head()

     kepoi_name  koi_prad  koi_insol  koi_score     size_category
8817  K06863.01      0.95       4.20        1.0        earth-like
0     K00752.01      2.26      93.59        1.0  super-earth-like
7612  K03371.02      1.00      50.05        1.0        earth-like
4     K00755.01      2.75     926.16        1.0  super-earth-like
5     K00756.01      3.90     114.81        1.0      neptune-like

Distributions

In [6]:
size_dist = df_confirmed['size_category'].value_counts().reset_index()
size_dist.columns = ['size_category','count']
size_dist

      size_category  count
0  super-earth-like   1240
1        earth-like    560
2      neptune-like    380
3         Gas-Giant    155

Stellar Energy

In [7]:
energy_bins = pd.cut(
    df_confirmed['koi_insol'],
    bins=[0,10,100,500,2000],
    labels=['Low','Moderate','High','Extreme']
)
energy_dist = energy_bins.value_counts().reset_index()
energy_dist.columns = ['energy_level', 'count']
energy_dist

  energy_level  count
0     Moderate    929
1         High    727
2          Low    335
3      Extreme    281

Confidence by size

In [8]:
confidence_by_size = df_confirmed.groupby('size_category')['koi_score'].mean().reset_index()
confidence_by_size

/tmp/ipykernel_635/2710155907.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  confidence_by_size = df_confirmed.groupby('size_category')['koi_score'].mean().reset_index()

      size_category  koi_score
0        earth-like   0.950879
1  super-earth-like   0.975742
2      neptune-like   0.964850
3         Gas-Giant   0.912239

Export and download clean csv

In [9]:
pd.DataFrame.to_csv(confidence_by_size, 'confidence_by_size.csv')
pd.DataFrame.to_csv(df_confirmed, 'confirmed_exoplanets.csv')
pd.DataFrame.to_csv(energy_dist, 'energy_dist.csv')
pd.DataFrame.to_csv(size_dist, 'size_dist.csv')

In [10]:
files.download("confirmed_exoplanets.csv")
files.download("size_dist.csv")
files.download("energy_dist.csv")
files.download("confidence_by_size.csv")